### ISSUE TITLE
Best way to use `rac_countObjects`?

### ISSUE THREAD

**Issue by bangedorrunt** [kastiglione/Parse-RACExtensions#11]
Hi guys,
I'm having a problem with how to use `rac_countObjects`. In my sample code method, what I did is get an `aFilteredPFLocationObjectsArray` from `previous signal` by `flattenMap`. I want to return a signal which value is a pair of `location` and `number of photos`. With ordinary `Parse Query`, I used `-countObjects` to **synchronously** get number of photo based on particular location. The problem is `-rac_countObjects` get data **asynchronously**, there is possibility my method return signal before `rac_countObjects` completed, hence no corresponding photo is counted.
How can I overcome this issue?

``` objc
- (RACSignal *)filteredPFLocationObjectsSignal:(NSArray *)aFilteredPFLocationObjectsArray {
    return [[RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        NSMutableArray *filteredArray = [NSMutableArray array];
        _.array(aFilteredPFLocationObjectsArray).each(^ (PFObject *pfLocationObject){
            PFRelation *photoRelation  = [pfLocationObject relationforKey:@"photos"];
            NSNumber *newNumber = [NSNumber numberWithInt:[[photoRelation query]countObjects]];
            NSDictionary *data = [NSDictionary dictionaryWithObjects:@[pfLocationObject, newNumber] forKeys:@[@"pfLocationObject", @"number"]];
            [filteredArray addObject:data];
        });
        [subscriber sendNext:filteredArray];
        [subscriber sendCompleted];
        return nil;
    }] deliverOn:[RACScheduler scheduler]];
}
```

**Edited 1:** Is using `zip:reduce` possible in this case?

**Comment by kastiglione** [comment]
I would map the locations into to a collection of `-rac_countObjects` signals, and use `+merge` to perform the queries concurrently. Finally, use `-collect` to combine each query result into single array.

_I've made the names a bit shorter for GitHub formatting readability_.

``` objc
- (RACSignal *)locationCounts:(NSArray *)locations {
    return [[RACSignal
        merge:[locations.rac_sequence map:^(PFObject *pfLocation) {
            PFRelation *photoRelation  = [pfLocation relationforKey:@"photos"];
            RACSignal *countSignal = [[photoRelation query] rac_countObjects];
            RACSignal *locationSignal = [RACSignal return:pfLocation];

            // Returns a RACTuple: (PFObject *, NSNumber *)
            return [locationSignal zipWith:countSignal];
        }]
        collect];
}
```

The main difference here is that this signal results in an array of tuples, which is a bit different, but to me is more appropriate than an array of dictionaries.

If you absolutely need an array of dictionaries, map the array like so:

``` objc
return [arrayOfTuples.rac_sequence map:^(RACTuple *tuple) {
    return @{ @"pfLocationObject": tuple.first, @"number": tuple.second };
}].array;
```

**Comment by kastiglione** [comment]
Just saw your edit about using `+zip:reduce:`. Yes, it would be possible to do it that way too, but I think using `+merge` (or possibly `+concat`) combined with `-collect` work better in this case.

**Comment by bangedorrunt** [comment]
Just as usual, you're awesome @kastiglione :star2: I have to go home now, it will take me around 3 hours and I will give you feedback really soon. One thing I found challenging is there are not many `ReactiveCocoa` resources to take references. I'm trying to get the hang of it day by day. It's already 3 months since I first started programming iOS. Very challenging, yet fascinating :)

**Comment by kastiglione** [comment]
:tophat: 

3 hours to get home? Damn that's a long trip. It's midnight for me now, so I won't be around to answer until tomorrow morning. 

And yeah, there is a lot of material to learn for iOS development. How did you come across ReactiveCocoa, and what made you decide to give it a shot?

**Comment by bangedorrunt** [comment]
Thanks so much @kastiglione,
1. I agree, 3 hours is killing me, that's why I hate going to uni :smile: 
2. It's been around 3 months ago since I have started learning `Objective-C` for the very first time (I know Java & some Web Programming Languages but not proficient), exactly right when I have my `Macbook Air` for the first time in my life. Once when I were doing research about how to run task in background using `dispatch` and `NSOperation class`, `ReactiveCocoa` showed up at [NSHipster/ReactiveCocoa](http://nshipster.com/reactivecocoa/). I was so curious about the name and read the article on that website. After navigating to `ReactiveCocoa GitHub Page`, I'm so excited about the way it is introduced right at `README.md`.

> One of the major advantages of RAC is that it provides a single, unified approach to dealing with asynchronous behaviors, including delegate methods, callback blocks, target-action mechanisms, notifications, and KVO.

The more I get to know `ReactiveCocoa`, the more I want to practice it. I have been heard countless time about **Functional Programming** when I studied `Javascript` (_curry_, _higher order function_...). So I decided to give it ago for my current graduated project. Honestly, `ReactiveCocoa` is still a new world to me even the underlying meaning of the authors when they develop the framework. Please correct me if I'm wrong, here is my humble reason why I want to learn `ReactiveCocoa`

> I just think `ReactiveCocoa` as a **Mouth-watering Recipe** in which **you are a chef, signals are food ingredients**. The best chef will know how to make use of all ingredients and combine them together to produce an amazing meal. Different chefs will have different taste so as different recipes. For me, when it comes to cooking term, `ReactiveCocoa` is perfectly matched with the famous saying: `The Less Is The More` :smile: 

Sorry, too much talking, Now time for analyzing your advice. If I understand correctly:
1. `+merge:` combine multiple signals into one single signal of signals
2. `location.rac_sequence` converts an array into a `RACSequence Stream` so you can transform the collection with `-map:` 
3. each `RACSequence value` is gonna be transformed into an `RACTuple value` which store a pair of `pfLocationSignal` and `countSignal`
4. Hence `[location.rac_sequence] is a`RACSequence Stream`which contains an array of`RACTuple`
5. But what I don't understand is why you use `+merge:` here because `[location.rac_sequence]` is not a signal of signals :worried: 

**Updated 01:** modified some mistakes 
**Updated 02:** I did finish convert my code based on your advice, it run very well. Still confused about `+merge:` and `-collect:` method

``` objc
PFQuery *photoQuery = [PFQuery queryWithClassName:@"Photo"];
//[photoQuery whereKey:@"author" equalTo:[PFUser currentUser]];
PFQuery *locationQuery = [PFQuery queryWithClassName:@"Location"];
//locationQuery.cachePolicy = kPFCachePolicyCacheThenNetwork;
[locationQuery selectKeys:@[@"latlng", @"address"]];
[locationQuery whereKey:@"creator" equalTo:[PFUser currentUser]];
[locationQuery whereKey:@"photos" matchesQuery:photoQuery];
[[[[locationQuery rac_findObjects]
   flattenMap:^ (NSArray *objects) {
       return [[RACSignal merge:[objects.rac_sequence map:^ (PFObject *pfLocationObject) {
           RACSignal *pfLocationObjectSignal = [RACSignal return:pfLocationObject];
           PFRelation *photoRelation = [pfLocationObject relationforKey:@"photos"];
           RACSignal *pfPhotoCounterSignal = [[photoRelation query] rac_countObjects];
           // Return a RACTuple:^ (PFObject *, NSNumber *)
           return [pfLocationObjectSignal zipWith:pfPhotoCounterSignal];
       }]] collect];
   }]
  flattenMap:^ (NSArray *objects) {
      _.array(objects).each(^ (RACTuple *args) {
          NSInteger number = [args.second integerValue];
          NSString *subtitle = [args.first objectForKey:@"address"];
          PFGeoPoint *locationGeo = [args.first objectForKey:@"latlng"];

          // Create Annotation Pin and add to MapView
          _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
          [annotationArray addObject:annotation];
          //[self._photoMapView addAnnotation:annotation];
      });
      return [RACSignal return:annotationArray];
  }] subscribeNext:^ (NSMutableArray *anAnnotationArray) {
     // Show Map View
     [hud hide:YES];
}];
```

**Comment by kastiglione** [comment]
First, I noticed a comment might have been misleading. The expression `[locationSignal zipWith:countSignal]` creates a signal that sends tuples.

It might help if I broke up the `+merge:` code a little bit. Using my original example:

``` objc
- (RACSignal *)locationCounts:(NSArray *)locations {
    RACSequence *photoCountRequests = [locations.rac_sequence map:^(PFObject *pfLocation) {
        PFRelation *photoRelation  = [pfLocation relationforKey:@"photos"];
        RACSignal *countSignal = [[photoRelation query] rac_countObjects];
        RACSignal *locationSignal = [RACSignal return:pfLocation];

        // Returns a *signal* that sends a single RACTuple: (PFObject *, NSNumber *)
        return [locationSignal zipWith:countSignal];
    }];

    return [[RACSignal merge:photoCountRequests] collect];
}
```

The sequence `photoCountRequests` could just as easily be an array instead of a sequence, but as you identified, I used `.rac_sequence` in order to use the `-map:` function. **You can just as easily use Underscore to map the locations array into another array**. Actually, let's do that for comparison:

``` objc
- (RACSignal *)locationCounts:(NSArray *)locations {
    NSArray *photoCountRequests = _.array(locations)
        .map(^ (PFObject *pfLocation) {
            PFRelation *photoRelation  = [pfLocation relationforKey:@"photos"];
            RACSignal *countSignal = [[photoRelation query] rac_countObjects];
            RACSignal *locationSignal = [RACSignal return:pfLocation];

            // Returns a RACTuple: (PFObject *, NSNumber *)
            return [locationSignal zipWith:countSignal];
        })
        .unwrap;

    return [[RACSignal merge:photoCountRequests] collect];
}
```

Now about `+merge:`. It's like a union of signals. Give it a collection (ex: array or sequence) of signals, and it produces a unified signal which passes through all values sent from any of the underlying signals. In this case, the signal will send the results from the underlying `rac_countObjects` query. Strictly speaking, this isn't a "signal of signals", since the signals involved all send regular values (in this case tuples), not signals.

Does that help?

**Comment by kastiglione** [comment]
Oh and by the way, I love your how you illustrated the chef analogy. Not bad!

**Comment by bangedorrunt** [comment]
Thanks @kastiglione :star2: , I totally understand now :+1: , I'm about to update my post but got your answer in the nick of time, so I guess it's morning now at your place :smile: . It's 3:30 am in Australia now. What I have been trying to do is learn to apply your pattern in other part. Before I close this issue, there is one last question I would like you to give me your feedback.
In a `UITableViewController`, I want to remove some `PFObject`s that is related to each other. As far as you know, `Parse` doesn't support to remove cascade objects. Here is my previous line of code that worked:

``` objc
[[photoRelation query] findObjectsInBackgroundWithBlock:^(NSArray *pfPhotoObjects, NSError *error) {
            [pfPhotoObjects enumerateObjectsUsingBlock:^(id pfPhotoObject, NSUInteger idx, BOOL *stop) {
                PFRelation *commentRelation = [pfPhotoObject relationforKey:@"comment"];
                [[commentRelation query] findObjectsInBackgroundWithBlock:^(NSArray *pfCommentObjects, NSError *error) {
                    [pfCommentObjects enumerateObjectsUsingBlock:^(id pfCommentObject, NSUInteger idx, BOOL *stop) {
                        [pfCommentObject deleteInBackground];
                    }];
                }];
                [pfPhotoObject deleteInBackground];
            }];
            [pfLocationObject removeObjectForKey:@"photos"];
            [pfLocationObject saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
                [self loadObjects];
            }];
}];
```

Here is my new line of code based on your pattern:

``` objc
__block PFObject *pfLocationObject = [self.objects objectAtIndex:indexPath.row];
        PFRelation *photoRelation = [pfLocationObject relationforKey:@"photos"];
        [[[[photoRelation query] rac_findObjects] flattenMap:^ (NSArray *pfPhotoObjects) {
            return [[[RACSignal merge:[pfPhotoObjects.rac_sequence map:^ (PFObject *pfPhotoObject) {
                RACSignal *pfRemoveLocationObjectSignal = [pfLocationObject rac_delete];
                RACSignal *pfRemovePhotoObjectSignal = [pfPhotoObject rac_delete];
                PFRelation *commentRelation = [pfPhotoObject relationforKey:@"comment"];
                RACSignal *pfRemoveCommentObjectSignal = [[[commentRelation query] rac_findObjects] flattenMap:^ (NSArray *pfCommentObjects) {
                    return [[[RACSignal merge:[pfCommentObjects.rac_sequence map:^ (PFObject *pfCommentObject) {
                        return [pfCommentObject rac_delete];
                    }]] collect] deliverOn:[RACScheduler scheduler]];
                }];
                // Return a RACTuple: (PFObject *, NSArray *)
                return [RACSignal zip:@[pfRemoveCommentObjectSignal, pfRemoveLocationObjectSignal, pfRemovePhotoObjectSignal]];
            }]] collect] deliverOn:[RACScheduler scheduler]];
        }] subscribeCompleted:^ {
            [self loadObjects];
}];
```

As you can see, the later seems to be more complicated than the former. What is your point of view in this case?

**Comment by kastiglione** [comment]
You can make it shorter by using [`+rac_deleteAll:`](https://github.com/kastiglione/Parse-RACExtensions/blob/e2fc14693164cc653119cec4c05e95957fdac5da/Parse-RACExtensions/PFObject%2BRACExtensions.h#L42-48) to delete the photos and their comments.

``` objc
PFObject *location = [self.objects objectAtIndex:indexPath.row];
PFRelation *photoRelation = [location relationforKey:@"photos"];
[[[[[[photoRelation query] rac_findObjects]
    flattenMap:^(NSArray *photos) {
        return [[RACSignal
            merge:[photos.rac_sequence map:^(PFObject *photo) {
                PFRelation *commentRelation = [photo relationforKey:@"comment"];
                return [[[commentRelation query] rac_findObjects]
                    flattenMap:^(NSArray *comments) {
                        return [PFObject rac_deleteAll:comments];
                    }];
            }]]
            concat:[PFObject rac_deleteAll:photos]];
    }]
    doCompleted:^{
        [location removeObjectForKey:@"photos"];
    }]
    concat:[location rac_save]]
    subscribeCompleted:^{
        [self loadObjects];
    }];
```

Extracting methods would be my approach to making this code simpler. There are some patterns you could extract, perhaps reusability, or perhaps just to make the code more declarative. For example, imagine `-rac_objectsInRelationForKey:`, and even better, `-rac_deleteRelationForKey:`. Feel free to do pull requests for these :smirk:

**Comment by bangedorrunt** [comment]
That would be great idea @kastiglione :100: . As I'm looking into your advice, I see you use `-concat:` to combine signals from `+merge:`. According to my understanding, this is used to combine values from differents streams (here is signals from `+merge:` and `-rac_deleteAll:`) and then `-flatten:` to return a new single signal. Am I correct?

On top of that, I'm more than happy If I could contribute to your project. I will try to do it after I finish my course in November :smile:

**Comment by kastiglione** [comment]
I think your understanding is correct, except the `-flatten:` part. Did you mean `-flattenMap:`?

You can think of `-concat` as being just like string concatenation. A + B. In this case, there's the `+merge` signal, which is deleting all the comments for the array of photos, and then, upon completion, the `+rac_deleteAll:` signal begins it's work, deleting the photos themselves. Makes sense or does it raise more questions?

**Comment by bangedorrunt** [comment]
Thanks @kastiglione , Yes, I did mean `-flattenMap:` There's only one question that bugs me is I don't see any difference between `-concat:` and `-then:` :question: :question: :question:

**Comment by kastiglione** [comment]
Yep, `-concat:` vs `-then:` can be a confusing. In RAC 1.x, `-then:` was called `-sequenceNext:`, which was found to be confusing, hence the name change. If you look at the source for `-then:`, you'll see the answer as to how the two methods differ. For signals that don't send values, `-concat:` and `-then:` are interchangeable.

**Comment by bangedorrunt** [comment]
Thanks heaps @kastiglione  for your clarification. I will close this issue now :smiley:
