### ISSUE TITLE
Thought about synchronous request!

### ISSUE THREAD

**Issue by bangedorrunt** [kastiglione/Parse-RACExtensions#12]
Hi Dave,

Since the extension currently only support for asynchronous request, do you think it is a need to implement synchronous request?
Because I think some people might find it useful (not me just because I haven't face the situation that need synchronous request :laughing: )
Moreover, there is other part might be useful including `PFImage` & `PFFile`.

**Comment by kastiglione** [comment]
The Parse API has support for synchronous requests. What did you have in mind that this project could add on top of those synchronous requests?

**Comment by bangedorrunt** [comment]
@kastiglione I maybe was thinking too much. Currently I found no use to have synchronous requests for this project. Sorry about that :worried:
