### ISSUE TITLE
Remove Parse SDK NSError* Normalization?

### ISSUE THREAD

**Issue by mhupman** [kastiglione/Parse-RACExtensions#16]
[PFRACCallbacks.m#L16](/kastiglione/Parse-RACExtensions/blob/master/Parse-RACExtensions/PFRACCallbacks.m#L16) looks like it was written to handle a situation where the `NSError*` returned from the ParseSDK didn't set the `NSLocalizedDescriptionKey` and instead stuffed the string representation of the underlying error into `userInfo[@"error"]`

However, NSErrors returned by ParseSDK 1.2.15+ do have a `localizedDescription` set.  So, the question is, should we remove PFRACNormalizeError completely?  Alternatively, we could leave it in place but modify it to only handle the `error == nil` case.

FWIW, I checked the Parse iOS SDK release notes but didn't see anything about a change in how `NSError` were generated, so I'm assuming this code was originally written as a workaround for a time when Parse SDK errors did not include a localized description.

**Comment by kastiglione** [comment]
Definitely shouldn't be blindingly assigning to `NSLocalizedDescriptionKey` like that!

I'm fine with removing it altogether and passing through even `nil` errors. I was only concerned with surfacing the value under the `@"error"` key.

**Comment by mhupman** [comment]
Ok, I'll work on removing it.  It would be nice if the Parse iOS SDK populated the `NSUnderlyingErrorKey` with the actual `NSError*` object.  As it stands, the string representation in `@"error"` isn't suitable for user presentation or parsing.

**Comment by kastiglione** [comment]
Closed by #17.
