### ISSUE TITLE
Update Parse dependency to 1.3.0

### ISSUE THREAD

**Issue by hokster7** [kastiglione/Parse-RACExtensions#18]
Current version of Parse is 1.3.0.

http://cocoapods.org/?q=parse

**Comment by kastiglione** [comment]
Mind opening a pull request? I'd be happy to accept.

**Comment by hokster7** [comment]
Actually I think it's better to see what happens to Cocoapods/Specs#11294 before updating.

**Comment by kastiglione** [comment]
:+1:

**Comment by ghost** [comment]
All done, please use the official spec -> "Parse" with version ~> 1.3.0.1

**Comment by kastiglione** [comment]
:ship:
