### ISSUE TITLE
rac_findObjects doesn't react well to multiple subscribers

### ISSUE THREAD

**Issue by hokster7** [kastiglione/Parse-RACExtensions#20]
I would like to use Parse RACExtensions to have so that I'll know

```
PFQuery *query = ...;
self.initializationSignal = [query rac_findObjects];
```

When I subscribe two subscribers: one `subscribeNext:` and one `subscribeCompleted:`, then everything works fine.

If instead of `subscribeCompleted:` I use `waitUntilCompleted:`, or if I add one more subscriber (doesn't matter whether it's 'next' or 'completed'), then I get this error from Parse:

```
This query has an outstanding network connection. You have to wait until it's done.
```

**Comment by kastiglione** [comment]
Each subscriber will cause a query to be sent to the server, hence that error message. If you want to have one query, with multiple subscribers sharing the one query, then the typical way to do that is through `RACMulticastConnection`.

**Comment by hokster7** [comment]
Ahh so is that what `RACMulticastConnection` is for? For standard usages of RAC multiple subscribers seemed to work fine every time. I'll give it a shot. Thanks @kastiglione!

**Comment by hokster7** [comment]
@kastiglione I've still got a problem. The simplest thing I have tried is the following:

``` objc
PFQuery *query = [PFQuery queryWithClassName:@"Foobar"];
query.cachePolicy = kPFCachePolicyCacheThenNetwork;

RACSignal *multicastConnectionSignal = [[[query rac_findObjects] publish] signal];
[multicastConnectionSignal waitUntilCompleted:nil];   // hangs...
...
```

I'm using `-waitUntilCompleted:` because just like in #19, I want to make these synchronous for us in my unit tests so that I can run this code conveniently.

**Comment by hokster7** [comment]
Okay! I got it working — I clearly just forgot to call `-connect` or  `-autoconnect` on the connection before subscribing. No wonder nothing was happening. Plus, https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1495 explains why `-waitUntilCompleted` was hanging.

**Comment by kastiglione** [comment]
:octocat:
