### ISSUE TITLE
rac_refresh shouldn't be deprecated.

### ISSUE THREAD

**Issue by hokster7** [kastiglione/Parse-RACExtensions#24]
May be they un-deprecated the method at some point? The current API docs: 

https://parse.com/docs/ios/api/Classes/PFObject.html#//api/name/refreshInBackgroundWithBlock:

**Comment by kastiglione** [comment]
The header file says:

> // Deprecated and intentionally not available on the new OS X SDK

That's what I based that off. I'll ask and find out.

**Comment by kastiglione** [comment]
Actually, let's try this:

cc @nlutsenko-fb: Is `-[PFObject refresh]` deprecated, or are the header docs wrong?

**Comment by kastiglione** [comment]
Just heard from @nlutsenko-fb, `-refresh` is deprecated, but the API docs don't properly reflect that.

**Comment by ghost** [comment]
'refresh' methods on PFObject are deprecated and were like that for a long time (I believe over a year).

This is indeed a bug in API reference.
Thanks for catching it. We'll fix it asap.

**Comment by hokster7** [comment]
@nlutsenko-fb @kastiglione Alright thanks for clearing it up guys
