### ISSUE TITLE
rac_findObjects just hangs with firstOrDefault

### ISSUE THREAD

**Issue by hokster7** [kastiglione/Parse-RACExtensions#25]
Why?

I don't want to use the synchronous SDK API because I want to compose my signal with other parts of code asynchronously as well.

Basically what my code does:

``` objc
PFQuery *query = [PFQuery queryWithClassName:...];

NSArray *objects = [query findObjects];
DDLogInfo(@"1. got objects %@", objects);                  // works

objects = [[query rac_findObjects] first];
DDLogInfo(@"2. got objects with RAC: %@", objects); // HANGS
```

**Comment by kastiglione** [comment]
Apologies for not answering this in a timely manner.

I almost never use the synchronous methods, so I'm not sure why this is. I don't know if I'll have any time soon to investigate.

Hopefully you've found a solution and we can just close this issue. If not, let me know.

**Comment by hokster7** [comment]
Hmm. Yeah I think synchronous methods are just a bad idea since it'll hang the main thread and cause deadlocks. Just don't use `first`.

**Comment by kastiglione** [comment]
:+1:
